---
- name: Remove pyenv installed with Homebrew
  homebrew:
    path: "{{ pyenv_brew_path | default(omit) }}"
    name: pyenv
    state: absent

- name: Remove pyenv-virtualenv installed with Homebrew
  homebrew:
    path: "{{ pyenv_brew_path | default(omit) }}"
    name: pyenv-virtualenv
    state: absent

- name: Remove pyenv-virtualenvwrapper installed with Homebrew
  homebrew:
    path: "{{ pyenv_brew_path | default(omit) }}"
    name: pyenv-virtualenvwrapper
    state: absent
